<?php

return array(
    'uxu-type-blob-1'   => 'Type 1',
    'uxu-type-blob-2'   => 'Type 2',
    'uxu-type-blob-3'   => 'Type 3',
    'uxu-type-blob-4'   => 'Type 4',
    'uxu-type-blob-5'   => 'Type 5',
    'uxu-type-blob-6'   => 'Type 6',
    'uxu-type-blob-7'   => 'Type 7',
    'uxu-type-blob-8'   => 'Type 8',
    'uxu-type-blob-9'   => 'Type 9',
    'uxu-type-blob-10'   => 'Type 10',
    'uxu-type-blob-11'   => 'Type 11',
    'uxu-type-blob-12'   => 'Type 12',
    'uxu-type-blob-13'   => 'Type 13',
    'uxu-type-blob-14'   => 'Type 14',
    'uxu-type-blob-15'   => 'Type 15',
    'uxu-type-blob-16'   => 'Type 16',
    'uxu-type-blob-17'   => 'Type 17',
    'uxu-type-blob-18'   => 'Type 18',
    'uxu-type-blob-19'   => 'Type 19',
    'uxu-type-blob-20'   => 'Type 20',
    'uxu-type-blob-21'   => 'Type 21',
);
